# Generated by Nitro from public/.htaccess.tpl — __BASE__ is replaced with the
# app base URL at generate time so paths resolve correctly for both production
# (/) and preview (/pr-<n>/) builds.

# HTTP security headers (FIND-01 of security-audit)
# Apache mod_headers must be enabled on the host.

<IfModule mod_headers.c>
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
</IfModule>

# Custom error pages (prerendered Nuxt routes).
ErrorDocument 404 __BASE__404/index.html
ErrorDocument 410 __BASE__410/index.html

# Permanently removed URL ranges — return 410 Gone so search engines drop them
# from their index faster than they would for 404. The body is served from the
# ErrorDocument 410 above.
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase __BASE__
    RewriteRule ^tags(/.*)?$  - [G,L,NC]
    RewriteRule ^en(/.*)?$    - [G,L,NC]
    RewriteRule ^legal/?$     - [G,L,NC]
</IfModule>
