# Generated by Nitro from public/.htaccess.tpl — __BASE__ is replaced with the
# app base URL at generate time so paths resolve correctly for both production
# (/) and preview (/pr-<n>/) builds.

# HTTP security headers (FIND-01 of security-audit)
# Apache mod_headers must be enabled on the host.

<IfModule mod_headers.c>
    Header always set X-Frame-Options "DENY"
    Header always set X-Content-Type-Options "nosniff"
    Header always set Referrer-Policy "strict-origin-when-cross-origin"
    Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    Header always set Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"
</IfModule>

# Cache policy. The host applies a blanket one-year max-age to every file. That
# is right for hashed /_nuxt/ assets but wrong for HTML, feeds and crawler files
# (sitemap.xml, rss.xml, robots.txt, llms.txt): browsers and feed readers would
# keep a stale copy until a hard refresh. Force revalidation for those instead;
# ETag / Last-Modified turn repeat requests into cheap 304s.
<IfModule mod_headers.c>
    <FilesMatch "\.(html|xml|txt)$">
        Header set Cache-Control "no-cache"
    </FilesMatch>
</IfModule>

# Custom error pages (prerendered Nuxt routes).
ErrorDocument 404 __BASE__404/index.html
ErrorDocument 410 __BASE__410/index.html

# Permanently removed URL ranges — return 410 Gone so search engines drop them
# from their index faster than they would for 404. The body is served from the
# ErrorDocument 410 above.
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteBase __BASE__
    # Legacy Hugo site (hugo-theme-stack): German content at the root with
    # posts under /p/, pagination under /page/, plus the theme's list pages;
    # the English mirror lived under /en/.
    RewriteRule ^p(/.*)?$          - [G,L,NC]
    RewriteRule ^page(/.*)?$       - [G,L,NC]
    RewriteRule ^tags(/.*)?$       - [G,L,NC]
    RewriteRule ^categories(/.*)?$ - [G,L,NC]
    RewriteRule ^archives(/.*)?$   - [G,L,NC]
    RewriteRule ^search(/.*)?$     - [G,L,NC]
    RewriteRule ^about(/.*)?$      - [G,L,NC]
    RewriteRule ^en(/.*)?$         - [G,L,NC]
    RewriteRule ^legal/?$          - [G,L,NC]
    # Labs that were removed from the current site.
    RewriteRule ^labs/watch-wise/?$    - [G,L,NC]
    RewriteRule ^labs/tv-show-bingo/?$ - [G,L,NC]
    RewriteRule ^labs/fmeyer-dev/?$    - [G,L,NC]
</IfModule>
